include ../Makefile.tests_common

BOARD ?= nrf52dk

RIOTBASE ?= $(CURDIR)/../..

USEMODULE += srf04
#USEMODULE += atmega_pcint1
USEMODULE += periph_gpio
USEMODULE += periph_gpio_irq
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
