#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h> 
#include <ctype.h>

typedef struct character_definition_s
{
    int length;
    unsigned char data[127]; 
} character_definition_t;

typedef struct font_definition_s
{
    int interspacing;
    char name[128];
    character_definition_t characters[256]; 
} font_definition_t;

static void error(const char* format, ...)
{
    char message[1024];
    va_list args;
    va_start(args, format);
    vsprintf(message, format, args);
    va_end(args);
    
    fputs(message, stderr);
    exit(1);
}

static int is_comment_line(const char* line)
{
    return (line[0] == '#' &&  line[1] != ':') || line[0] =='\n' || line[0] == 0;
}

static int get_parameter(const char* line, char* name, char* value)
{
    return sscanf(line, "%[^=]=%s", name, value) == 2;
}

static char get_definition_start(const char* line)
{
    char c = 0;

    if(line[1]==':')
    {
        c = line[0];
    }

    return c;
}

static font_definition_t parse_font_file(const char* file_name)
{
    font_definition_t fd = {0};
    character_definition_t* active_character = NULL;
    int bit = 0;
    char line[128];
    FILE* font_file = fopen(file_name, "r");
    int line_nr = 0;
    
    if(font_file == NULL)
    {
        error("Unable to open font file \"%s\".\n", file_name);
    }
 
    while(fgets(line, sizeof(line), font_file))
    {
        char param_name[128]= {0};
        char param_value[128]= {0};
        const char* line_start = line;

        while(isspace(*line_start))
        {
            ++line_start;
        }
        
        ++line_nr;
        
        if(is_comment_line(line))
        {
            continue;
        }        
        
        if(get_parameter(line_start, param_name, param_value))
        {
            if(strcmp(param_name,"interspacing") == 0)
            {
                fd.interspacing = atoi(param_value);
            }
            else if(strcmp(param_name,"name") == 0)
            {
                strcpy(fd.name, param_value);
            }
            else
            {
                error("Unknown parameter \"%s\" at line %d.\n", param_name, line_nr);
            }
        }
        else
        {
            char c = get_definition_start(line);
            if(c)
            {
                active_character = fd.characters + c;

                if(active_character->length != 0)
                {
                    error("Redefinition at line %d; character '%c' is already defined.\n", 
                          line_nr, c);
                }

                bit = 0x01;
            }
            else
            {
                if(active_character)
                {
                    const char* p = line_start;
                    int i = 0;

                    if(bit > 0x80)
                    {
                        error("Character height of 8 pixels exceeded at line %d.\n", line_nr);
                    }

                    while(*p == '.' || *p=='*')
                    {
                        if(*p == '*')
                        {
                            active_character->data[i] |= bit;
                        }

                        ++p;
                        ++i;
                    }

                    if(bit == 0x01)
                    {
                        active_character->length = i;
                    }
                    else if(i != active_character->length)
                    {
                        error("Inconsistent character width at line %d.\n", line_nr);
                    }

                    bit <<= 1;
                }
                else
                {
                    error("Don't know what to do at line %d.\n", line_nr);
                }                
            }

        }
    }
    
    fclose(font_file);

    return fd;
}

static void generate_code(FILE* output, const font_definition_t* fd)
{
    int first_character = -1;
    int last_character = -1;
    int offset = 0;
    int offsets[257] = {0};
    int i = 0;
    int j = 0;

    fprintf(output,
            "/* Generated by GLCD_FontGenerator */\n"
            "\n"
            "#ifndef INCLUDED_%s_H\n"
            "#define INCLUDED_%s_H\n"
            "\n"
            "#include \"glcd.h\"\n"
            "\n"
            "#ifndef PROGMEM\n"
            "#define PROGMEM\n"
            "#endif\n"
            "\n"
            "static GLCD_FLASH_ARRAY(char, %s_data) =\n"
            "{\n",
            fd->name,
            fd->name,
            fd->name
           );

    for(i = 0; i < sizeof(fd->characters)/sizeof(fd->characters[0]); ++i)
    {
        const character_definition_t* cd = fd->characters + i;
        
        if(cd->length > 0)
        {
            if(first_character < 0)
            {
                first_character = i;
            }

            last_character = i;

            fputs("    ", output);
            for(j = 0; j < cd->length; ++j)
            {
                fprintf(output,"0x%02X, ", cd->data[j]); 
            }

            if(i>= 32 && i < 128)
            {
                fprintf(output,"/* %c */ ", i);
            }

            fputs("\n", output);
        }

        offsets[i] = offset;
        offset += cd->length;
    }

    fprintf(output,
            "};\n"
            "\n"
            "static GLCD_FLASH_ARRAY(glcd_font_data_ptr, %s_lookup) =\n"
            "{\n",
            fd->name);

    for(i = first_character; i <= last_character; ++i)
    {
        fprintf(output,
                "    %s_data + %d,\n",
                fd->name, 
                offsets[i]);                
    }

    fprintf(output, 
            "    %s_data + %d /* end */\n",
            fd->name,
            offset);


    fprintf(output,
            "};\n"
            "\n"
            "static const glcd_font_t %s PROGMEM = {%d, %d, %s_lookup};\n"
            "\n"
            "#endif\n",
            fd->name,
            first_character,
            fd->interspacing,
            fd->name);

    if(output != stdout)
    {
        printf("Font data size: %d bytes.\n", 
               offset + (1 + last_character - first_character) * 2);
    }
}

int main(int argc, char* argv[])
{
    FILE* output_file = stdout;
    font_definition_t font_definition;
    
    if(argc < 2)
    {
        error("No font file specified.\n"
              "\n"
              "Usage:\n"
              " %s <input_file> [<output_file>]\n");
    }

    if(argc > 2)
    {
        output_file = fopen(argv[2], "w");

        if(output_file == NULL)
        {
            error("Cannot write to: \"%s\"\n", argv[2]);
        }
    }
    
    font_definition = parse_font_file(argv[1]);

    generate_code(output_file, &font_definition);

    if(output_file != stdout)
    {
        fclose(output_file);
    }
    
    return 0;
}