/* Generated by GLCD_FontGenerator */

#ifndef INCLUDED_proportional_font_H
#define INCLUDED_proportional_font_H

#include "glcd.h"

#ifndef PROGMEM
#define PROGMEM
#endif

static GLCD_FLASH_ARRAY(char, proportional_font_data) =
{
    0x00, /*   */ 
    0x00, 0x5F, /* ! */ 
    0x03, 0x00, 0x03, /* " */ 
    0x80, 0x40, /* , */ 
    0x08, 0x08, /* - */ 
    0x40, /* . */ 
    0x3E, 0x41, 0x41, 0x3E, /* 0 */ 
    0x00, 0x42, 0x7F, 0x40, /* 1 */ 
    0x62, 0x51, 0x49, 0x46, /* 2 */ 
    0x41, 0x49, 0x49, 0x36, /* 3 */ 
    0x18, 0x14, 0x12, 0x7F, /* 4 */ 
    0x47, 0x45, 0x45, 0x39, /* 5 */ 
    0x3C, 0x4A, 0x49, 0x30, /* 6 */ 
    0x01, 0x71, 0x0D, 0x03, /* 7 */ 
    0x36, 0x49, 0x49, 0x36, /* 8 */ 
    0x06, 0x49, 0x29, 0x1E, /* 9 */ 
    0x48, /* : */ 
    0x60, 0x1C, 0x13, 0x1C, 0x60, /* A */ 
    0x7F, 0x49, 0x49, 0x36, /* B */ 
    0x3E, 0x41, 0x41, 0x22, /* C */ 
    0x7F, 0x41, 0x41, 0x3E, /* D */ 
    0x7F, 0x49, 0x49, 0x41, /* E */ 
    0x7F, 0x09, 0x09, 0x01, /* F */ 
    0x3E, 0x41, 0x49, 0x7A, /* G */ 
    0x7F, 0x08, 0x08, 0x7F, /* H */ 
    0x7F, /* I */ 
    0x40, 0x40, 0x3F, /* J */ 
    0x7F, 0x08, 0x14, 0x63, /* K */ 
    0x7F, 0x40, 0x40, /* L */ 
    0x7F, 0x02, 0x0C, 0x02, 0x7F, /* M */ 
    0x7F, 0x06, 0x18, 0x7F, /* N */ 
    0x3E, 0x41, 0x41, 0x3E, /* O */ 
    0x7F, 0x09, 0x09, 0x06, /* P */ 
    0x3E, 0x41, 0x21, 0x5E, /* Q */ 
    0x7F, 0x09, 0x19, 0x66, /* R */ 
    0x46, 0x49, 0x49, 0x31, /* S */ 
    0x01, 0x01, 0x7F, 0x01, 0x01, /* T */ 
    0x3F, 0x40, 0x40, 0x3F, /* U */ 
    0x07, 0x18, 0x60, 0x18, 0x07, /* V */ 
    0x7F, 0x20, 0x18, 0x20, 0x7F, /* W */ 
    0x63, 0x14, 0x08, 0x14, 0x63, /* X */ 
    0x03, 0x04, 0x78, 0x04, 0x03, /* Y */ 
    0x71, 0x49, 0x45, 0x43, /* Z */ 
    0x20, 0x54, 0x54, 0x78, /* a */ 
    0x7F, 0x44, 0x44, 0x38, /* b */ 
    0x38, 0x44, 0x44, 0x44, /* c */ 
    0x38, 0x44, 0x44, 0x7F, /* d */ 
    0x38, 0x54, 0x54, 0x58, /* e */ 
    0x7E, 0x09, /* f */ 
    0x18, 0xA4, 0xA4, 0x7C, /* g */ 
    0x7F, 0x04, 0x04, 0x78, /* h */ 
    0x7D, /* i */ 
    0x80, 0x7D, /* j */ 
    0x7F, 0x10, 0x28, 0x44, /* k */ 
    0x7F, /* l */ 
    0x7C, 0x04, 0x78, 0x04, 0x78, /* m */ 
    0x7C, 0x04, 0x04, 0x78, /* n */ 
    0x38, 0x44, 0x44, 0x38, /* o */ 
    0xFC, 0x24, 0x24, 0x18, /* p */ 
    0x18, 0x24, 0x24, 0xFC, /* q */ 
    0x7C, 0x08, 0x04, /* r */ 
    0x48, 0x54, 0x54, 0x24, /* s */ 
    0x3F, 0x44, /* t */ 
    0x3C, 0x40, 0x40, 0x7C, /* u */ 
    0x1C, 0x60, 0x1C, /* v */ 
    0x1C, 0x60, 0x10, 0x60, 0x1C, /* w */ 
    0x44, 0x28, 0x10, 0x28, 0x44, /* x */ 
    0x1C, 0xA0, 0xA0, 0x7C, /* y */ 
    0x44, 0x64, 0x54, 0x4C, 0x44, /* z */ 
};

static GLCD_FLASH_ARRAY(glcd_font_data_ptr, proportional_font_lookup) =
{
    proportional_font_data + 0,
    proportional_font_data + 1,
    proportional_font_data + 3,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 6,
    proportional_font_data + 8,
    proportional_font_data + 10,
    proportional_font_data + 11,
    proportional_font_data + 11,
    proportional_font_data + 15,
    proportional_font_data + 19,
    proportional_font_data + 23,
    proportional_font_data + 27,
    proportional_font_data + 31,
    proportional_font_data + 35,
    proportional_font_data + 39,
    proportional_font_data + 43,
    proportional_font_data + 47,
    proportional_font_data + 51,
    proportional_font_data + 52,
    proportional_font_data + 52,
    proportional_font_data + 52,
    proportional_font_data + 52,
    proportional_font_data + 52,
    proportional_font_data + 52,
    proportional_font_data + 52,
    proportional_font_data + 57,
    proportional_font_data + 61,
    proportional_font_data + 65,
    proportional_font_data + 69,
    proportional_font_data + 73,
    proportional_font_data + 77,
    proportional_font_data + 81,
    proportional_font_data + 85,
    proportional_font_data + 86,
    proportional_font_data + 89,
    proportional_font_data + 93,
    proportional_font_data + 96,
    proportional_font_data + 101,
    proportional_font_data + 105,
    proportional_font_data + 109,
    proportional_font_data + 113,
    proportional_font_data + 117,
    proportional_font_data + 121,
    proportional_font_data + 125,
    proportional_font_data + 130,
    proportional_font_data + 134,
    proportional_font_data + 139,
    proportional_font_data + 144,
    proportional_font_data + 149,
    proportional_font_data + 154,
    proportional_font_data + 158,
    proportional_font_data + 158,
    proportional_font_data + 158,
    proportional_font_data + 158,
    proportional_font_data + 158,
    proportional_font_data + 158,
    proportional_font_data + 158,
    proportional_font_data + 162,
    proportional_font_data + 166,
    proportional_font_data + 170,
    proportional_font_data + 174,
    proportional_font_data + 178,
    proportional_font_data + 180,
    proportional_font_data + 184,
    proportional_font_data + 188,
    proportional_font_data + 189,
    proportional_font_data + 191,
    proportional_font_data + 195,
    proportional_font_data + 196,
    proportional_font_data + 201,
    proportional_font_data + 205,
    proportional_font_data + 209,
    proportional_font_data + 213,
    proportional_font_data + 217,
    proportional_font_data + 220,
    proportional_font_data + 224,
    proportional_font_data + 226,
    proportional_font_data + 230,
    proportional_font_data + 233,
    proportional_font_data + 238,
    proportional_font_data + 243,
    proportional_font_data + 247,
    proportional_font_data + 252 /* end */
};

static const glcd_font_t proportional_font PROGMEM = {32, 1, proportional_font_lookup};

#endif
